### ISSUE TITLE
Design issue for nodejs.org/download

### ISSUE THREAD

**Issue by iliakan** [nodejs/nodejs.org#1232]
Hi,

A friend of mine asked me how to get Node 7, because https://nodejs.org/en/download/ only has 6.
I couldn't find it on that page, so I went google and found https://nodejs.org/en/download/current/.

Then I discovered that both me and him (20+ years of programming xp) couldn't figure out that "Current" is a clickable button on that page.

Guess that's not only us who find these buttons "under-designed".

**Comment by gibfahn** [comment]
>Guess that's not only us who find these buttons "under-designed".

I'm sure you're not the only one (and it seems a reasonable request), although AFAIK you're the first person to raise it.

What do you think should change to make it more obvious that it's a button? Maybe it should have some shadow below to make stand out? That seems to be what Google suggest in their [material design guidelines](https://material.io/guidelines/components/buttons.html#buttons-button-types), and we seem to be going for quite a flat design, so maybe that would help?

**Comment by refack** [comment]
I would:
1. set the `.download-version-toggle { background-color: white; }`
2. increase the button's border radius and remove margin
```css
.download-version-toggle a {
    /* margin: 2px; */
    padding: 5px 2px;
    border-radius: 5px;
}
.download-version-toggle a:first-child { margin-bottom: 4px; }
```
3. optional remove the dark green border from `.download-version-toggle`

![image](https://cloud.githubusercontent.com/assets/96947/26279249/8af5910a-3d7c-11e7-9649-cd13d70b01f7.png)
