### ISSUE TITLE
doc: Docker - Shouldn't we use included npm ?

### ISSUE THREAD

**Issue by Glideh** [nodejs/nodejs.org#3504]
Instead of suggesting to use host's npm to [initialize a new node app](https://github.com/nodejs/nodejs.org/blob/3df18110ebc0721affbb6e34a23b69813f9af3cb/locale/en/docs/guides/nodejs-docker-webapp.md#create-the-nodejs-app), shouldn't we use the one included into the image that we are going to use ?

Example with a basic `docker-compose.yml`

```yml
version: '3'

services:
    app:
        image: node:15.1.0-alpine
        volumes:
            - ./app:/home/node/app
```

```bash
docker-compose run app npm init
```

Then

```bash
docker-compose run app npm install [...]
```

Maybe user doesn't have npm installed on his host or most likely not the same version
