### ISSUE TITLE
UI - Lines appear on top of the commit links on hover in the release notes

### ISSUE THREAD

**Issue by thlorenz** [nodejs/nodejs.org#652]
It's a minor issue, but I'm pretty sure you'd want to underline the link instead when I hover over it.

The below image shows the line when hovering over the first link.
![screen shot 2016-04-15 at 10 10 45 am](https://cloud.githubusercontent.com/assets/192891/14566327/cb322fbc-02f4-11e6-826c-734e33301a61.png)

Screenshot taken here: https://nodejs.org/en/blog/release/v4.3.1/

**Comment by Fishrock123** [comment]
Can confirm.

**Comment by hiroppy** [comment]
I think it is a difficult problem.
Because we can not attach `class` to this elements.(because it is unfolded in markdown by metalsmith)

I tried to use `{: .fuga}` but could not apply class selector in metalsmith;(

https://github.com/nodejs/nodejs.org/blob/master/layouts/css/base.styl#L32

**Comment by kahwee** [comment]
This does the trick:

```
a > code {
    padding: .25em;
}
```

It pads it as such where you cannot see the green background.

**Comment by hiroppy** [comment]
@kahwee I do not recommend it. Because it is not improved in IE11.

IE11 needs `.32em`.

**Comment by kahwee** [comment]
Good note. I didn't have IE to test on. This is one way too:

``` css
a[href*="/commit/"] {
    background: #f0f0f0;
}
```

**Comment by hiroppy** [comment]
nice :+1: 
however I notice [this page](https://nodejs.org/en/about/) has same problem... :cry: 
how do we resolve above?

**Comment by kahwee** [comment]
This doesn't scale well:

``` css
a[href*="/api/"], a[href*="/commit/"] {
    background-color: #f0f0f0;
}
```

What do you think?

**Comment by hiroppy** [comment]
I agree with your opinion. This code doesn't scale well.
The best is to attach a class but I think it difficult.
@fhemberger Do you have any thoughts?

**Comment by fhemberger** [comment]
This seems to work well (just a quick test):

``` css
a:hover code {
  background-color: transparent;
  color: #fff;
}
```

So the hover effect just looks the same as for regular links.
