### ISSUE TITLE
Use annotations to suppress false-positive security warnings

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#6974]
https://github.com/ossf/scorecard/blob/main/config/README.md#annotating-your-project

for example, in a `.github/scorecard.yml`

```yaml
annotations:
  - checks:
      - dangerous-workflow
    reasons:
      - reason: remediated # the workflow is dangerous but only run under maintainers verification and approval
```

Unsure if non-contributors can see these - so not labeling them `good first issue` for now
