### ISSUE TITLE
Get Code Coverage >= 90%

### ISSUE THREAD

**Issue by avivkeller** [nodejs/nodejs.org#7657]
**(Follow-up #7623)**

After completing the migration to Codecov, our code coverage will be approximately **74.53%**. I recommend the following action steps:

- [ ] Set a minimum enforcement threshold of **70% coverage** (See https://docs.codecov.com/docs/codecov-yaml)
- [ ] Work towards increasing overall code coverage to **95% or higher**
- [ ] Once achieved, enforce a minimum of **90% coverage**

**Comment by ShubhamOulkar** [comment]
Should I take on this?

**Comment by AugustinMauroy** [comment]
You can work on it

**Comment by ShubhamOulkar** [comment]
> * Set a minimum enforcement threshold of **70% coverage**

Hi @avivkeller, I am little confused with threshold and target. Do you mean target 70%? Because threshold works differently in [codecov threshold](https://docs.codecov.com/docs/common-recipe-list#ease-target-coverage)

My changes are going to be as follows,
```
coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  behavior: default
  require_changes: true
```
