### ISSUE TITLE
Improve doc readability

### ISSUE THREAD

**Issue by octref** [nodejs/nodejs.org#919]
- **URL**: https://nodejs.org/api/fs.html

This is how the doc looks on my 15 inch RMBP using half screen. Can't even show a full function definition.

Please improve your media queries or font-size. I'm not a mobile user.

![image](https://cloud.githubusercontent.com/assets/4033249/18818254/b74f4d9e-8329-11e6-83cd-762de6e1ff6d.png)

**Comment by phillipj** [comment]
I can confirm this doesn't look optimal on a retina macbook atm. This is the caused by a media query I assume is supposed to be targeting iPad-ish devices.

``` css
@media only screen and (max-width: 1024px) {
  #content {
    font-size: 2.5em;
    overflow: visible;
  }
  ..
}
```

https://github.com/nodejs/node/blob/master/doc/api_assets/style.css#L463

I don't have a iPad (retina or not) at hand, so I haven't been able to test if the big font size is neccessary on those devices.. It maybe time to re-visit some of these media queries.

/cc @nodejs/documentation
